curso/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('getregion/', views.getregion, name='getregion'),
    path('detalle/', views.detalle, name='detalle'),
]

web/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Comuna(models.Model):
    codigo_comuna = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    codigo_region = models.ForeignKey('Region', models.DO_NOTHING, db_column='codigo_region', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comuna'
        
    def __str__(self):
        return self.nombre


class Curso(models.Model):
    codigo_curso = models.CharField(primary_key=True, max_length=30)
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_termno = models.DateField(blank=True, null=True)
    codigo_comuna = models.ForeignKey(Comuna, models.DO_NOTHING, db_column='codigo_comuna', blank=True, null=True)
    codigo_plan_formativo = models.ForeignKey('PlanFormativo', models.DO_NOTHING, db_column='codigo_plan_formativo', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'curso'
    
    def __str__(self):
        return self.codigo_curso


class CursoModuloTutor(models.Model):
    codigo_curso = models.OneToOneField(Curso, models.DO_NOTHING, db_column='codigo_curso', primary_key=True)  # The composite primary key (codigo_curso, codigo_modulo, codigo_tutor) found, that is not supported. The first column is selected.
    codigo_modulo = models.ForeignKey('Modulo', models.DO_NOTHING, db_column='codigo_modulo')
    codigo_tutor = models.ForeignKey('Tutor', models.DO_NOTHING, db_column='codigo_tutor')

    class Meta:
        managed = False
        db_table = 'curso_modulo_tutor'
        unique_together = (('codigo_curso', 'codigo_modulo', 'codigo_tutor'),)


class Estudiante(models.Model):
    id_estudiante = models.IntegerField(primary_key=True)
    rut = models.CharField(max_length=15, blank=True, null=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    apellido_pat = models.CharField(max_length=30, blank=True, null=True)
    apellido_mat = models.CharField(max_length=30, blank=True, null=True)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    codigo_comuna = models.ForeignKey(Comuna, models.DO_NOTHING, db_column='codigo_comuna', blank=True, null=True)
    codigo_curso = models.ForeignKey(Curso, models.DO_NOTHING, db_column='codigo_curso', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'estudiante'
    
    


class Modulo(models.Model):
    codigo_modulo = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    duracion_horas = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'modulo'


class PlanFormativo(models.Model):
    codigo_plan_formativo = models.CharField(primary_key=True, max_length=30)
    descripcion = models.CharField(max_length=250, blank=True, null=True)
    duracion_horas = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'plan_formativo'


class PlanModulo(models.Model):
    codigo_plan_formativo = models.OneToOneField(PlanFormativo, models.DO_NOTHING, db_column='codigo_plan_formativo', primary_key=True)  # The composite primary key (codigo_plan_formativo, codigo_modulo) found, that is not supported. The first column is selected.
    codigo_modulo = models.ForeignKey(Modulo, models.DO_NOTHING, db_column='codigo_modulo')

    class Meta:
        managed = False
        db_table = 'plan_modulo'
        unique_together = (('codigo_plan_formativo', 'codigo_modulo'),)


class Region(models.Model):
    codigo_region = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'region'
        
    def __str__(self):
        return self.nombre


class Tutor(models.Model):
    codigo_tutor = models.IntegerField(primary_key=True)
    rut = models.CharField(max_length=15, blank=True, null=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    apellido_pat = models.CharField(max_length=30, blank=True, null=True)
    apellido_mat = models.CharField(max_length=30, blank=True, null=True)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    cargo = models.CharField(max_length=20, blank=True, null=True)
    codigo_comuna = models.ForeignKey(Comuna, models.DO_NOTHING, db_column='codigo_comuna', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tutor'

web/forms.py
from django import forms
from web.models import *

class MainForm(forms.Form):
    region_selector = forms.ModelChoiceField(queryset=Region.objects.all(), to_field_name='codigo_region',label="Región", widget=forms.Select(attrs={'class':'form-select'}), required=False, empty_label="Seleccione una región")
    curso_selector = forms.ModelChoiceField(queryset=Curso.objects.all(), to_field_name='codigo_curso',label="Curso", widget=forms.Select(attrs={'class':'form-select'}), required=False, empty_label="Seleccione un curso")

web/views.py
from django.shortcuts import render
from web.models import *
from web.forms import MainForm
from django.http import JsonResponse

# Create your views here.


def index(request): 
    estudiante_datos = Estudiante.objects.all()
    if request.method == 'POST': # Preguntamos si el formulario fue enviado
        forma = MainForm(request.POST)
        region_buscado = request.POST.get('region_selector')
        curso_buscado = request.POST.get('curso_selector')
        
        print(region_buscado, curso_buscado)
        if region_buscado: # Si hay una región seleccionada, filtramos los estudiantes por ella
            # Primero obtenemos las comunas de esa región
            comunas_en_region = Comuna.objects.filter(codigo_region=region_buscado)
            # Luego filtramos los estudiantes que están en esas comunas
            estudiante_datos = estudiante_datos.filter(codigo_comuna__in=comunas_en_region)

        if curso_buscado: # Si hay un curso seleccionado, filtramos los estudiantes que lo cursan
            estudiante_datos = estudiante_datos.filter(codigo_curso=curso_buscado) # Asumiendo que Estudiante tiene codigo_curso
            # O si el filtro es por la comuna asociada al curso seleccionado, tendríamos que buscar la comuna del curso
            # curso_obj = Curso.objects.get(codigo_curso=curso_buscado)
            # estudiante_datos = estudiante_datos.filter(codigo_comuna=curso_obj.codigo_comuna)
        # if curso_buscado != '':
        #     estudiante_datos = estudiante_datos.filter(codigo_curso = curso_buscado)

    else:
        forma = MainForm()
        estudiante_datos = []
    return render(request, 'form.html', {'estudiantes': estudiante_datos, 'form': forma})


def getregion(request):
    if request.method == "POST":
        codigo_region = request.POST['codigo_region']
        data = {}
        try:
            region = Region.objects.filter(codigo_region=codigo_region)
        except Exception:
            data['error_message'] = 'error'
            return JsonResponse(data)
        return JsonResponse(list(region.values('codigo_curso', 'title')), safe=False)


def detalle(request):
    codigo_curso = request.POST.get('detalle_id')
    print(codigo_curso)
    query = f"""
        select "codigo_curso" = {codigo_curso};
    """
    datos = Curso.objects.raw(query)

    return render(request, 'detalle.html', {'datos': datos[0]})

web/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CRUD_Django_Academia</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous" />
</head>

<body>
    <main>
        <div class="mt-4 container">
            {% block content %}
            {% endblock %}</div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>

</html>

web/templates/detalle.html
{% extends 'base.html' %}
{% block content %}
<h1>Detalles </h1>

<table class="table">
    <tbody>
        <tr>
            <th scope="row">Curso:</th>
            <td>{{ datos.curso }}</td>
        </tr>
        <tr>
            <th scope="row">Region:</th>
            <td>{{ datos.region }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

web/templates/form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST" class="py-0 px-1 d-flex">
    {% csrf_token %}
    {% for field in form %}
    <div class="div-field px-2">
        <label class="form-label my-0">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <div class="py-4">
        <button class="btn btn-primary py-1 " style="width: 90px" type="submit">
            Filtrar
        </button>
    </div>

</form>

{% include 'tabla.html' %}


{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
<script>
      $("#id_codigo_region_selector").change(function () {
          const codigoregion= $(this).val();  // cambiar por el nombre del id deseado
          console.log(codigoregion);
          $.ajax({                       //
              type: "POST",
              url: '{% url "getregion" %}',
              data: {
                  'codigo_region': codigoregion,       // Coloque el id a consultar
                  'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
              },
              success: function (data) {   // `data` tiene la respuesta a la consulta
                  let html_data = '<option value="">---------</option>';
                  data.forEach(function (data) {
                      html_data += `<option value="${data.nombre}">${data.nombre}</option>`
                  });
                  $("#id_curso_selector").html(html_data); // replace the contents of the topic input with the data that came from the server
              }
          });
      });
</script>
{% endblock javascript %}

{% endblock %}

web/templates/tabla.html
{% extends 'base.html' %}
{% block content %}

<div class="tabla-datos mt-5">
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Rut</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido Paterno</th>
                <th scope="col">Apellido Materno</th>
                <th scope="col">Código Curso</th>
                <th scope="col">Nombre Comuna</th>

            </tr>   
        </thead>
        <tbody>
            {% for item in estudiantes %}
            <tr>
                <th scope="row">{{item.id_estudiante}}</th>
                <td>{{item.rut}}</td>
                <td>{{item.nombre}}</td>
                <td>{{item.apellido_pat}}</td>
                <td>{{item.apellido_mat}}</td>
                <td>{{item.codigo_curso}}</td>
                <td>{{item.codigo_comuna}}</td>
                <td>
                    <form action="detalle/" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" type="submit" value="{{ item.track_id}}" name="detalle_id">Ver</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}